-- SignalDesk 003: seed the asset catalogue, aliases and verified sources.
-- GENERATED from src/config/assets-seed.ts and sources-seed.ts by `npm run seed -- --write-sql`. Do not edit by hand.

insert into public.assets (slug, name, asset_type, description_simple) values
  ('eur-usd', 'EUR/USD', 'currency_pair', 'How many US dollars one euro buys. Up means the euro is getting stronger against the dollar.'),
  ('gbp-usd', 'GBP/USD', 'currency_pair', 'How many US dollars one British pound buys. Up means sterling is getting stronger.'),
  ('usd-jpy', 'USD/JPY', 'currency_pair', 'How many Japanese yen one US dollar buys. Up means the dollar is stronger and the yen weaker.'),
  ('gold', 'Gold', 'commodity', 'The precious metal, often bought as a safe place for money when markets are nervous.'),
  ('silver', 'Silver', 'commodity', 'A precious metal also used heavily in industry, such as solar panels and electronics.'),
  ('oil', 'Crude oil', 'commodity', 'The price of crude oil (Brent and WTI benchmarks), driven by supply, demand and OPEC decisions.'),
  ('sp-500', 'S&P 500', 'index', 'An index of 500 large US companies, the most watched measure of the US stock market.'),
  ('nasdaq', 'Nasdaq', 'index', 'A US stock index dominated by technology companies.'),
  ('nvidia', 'NVIDIA', 'stock', 'Chipmaker whose graphics processors power much of today''s AI.'),
  ('apple', 'Apple', 'stock', 'Maker of the iPhone, Mac and related services; one of the world''s largest companies.'),
  ('tesla', 'Tesla', 'stock', 'Electric-car and battery company.'),
  ('bitcoin', 'Bitcoin', 'crypto', 'The largest cryptocurrency by market value.'),
  ('ethereum', 'Ethereum', 'crypto', 'The second-largest cryptocurrency network; its coin is called ether.'),
  ('fed', 'Federal Reserve', 'central_bank', 'The US central bank. It sets US interest rates to keep prices stable and jobs strong.'),
  ('ecb', 'European Central Bank', 'central_bank', 'The central bank for the euro area. It sets interest rates for the countries using the euro.'),
  ('boe', 'Bank of England', 'central_bank', 'The UK central bank. It sets UK interest rates.'),
  ('aud-usd', 'AUD/USD', 'currency_pair', 'How many US dollars one Australian dollar buys. Often moves with commodity prices and China.'),
  ('usd-cad', 'USD/CAD', 'currency_pair', 'How many Canadian dollars one US dollar buys. Up means the US dollar is stronger.'),
  ('usd-chf', 'USD/CHF', 'currency_pair', 'How many Swiss francs one US dollar buys. The franc is a classic safe haven.'),
  ('dxy', 'US Dollar Index', 'index', 'The US dollar against a basket of six major currencies. Up means the dollar is broadly stronger.'),
  ('natural-gas', 'Natural gas', 'commodity', 'Fuel for heating and power plants. Prices swing with weather, storage levels and LNG exports.'),
  ('copper', 'Copper', 'commodity', 'Industrial metal used in wiring and construction; often read as a gauge of global growth.'),
  ('dow-jones', 'Dow Jones', 'index', 'An index of 30 large US companies, the oldest widely followed US stock average.'),
  ('ftse-100', 'FTSE 100', 'index', 'An index of the 100 largest companies listed in London.'),
  ('dax', 'DAX', 'index', 'Germany''s main stock index of 40 large companies.'),
  ('nikkei-225', 'Nikkei 225', 'index', 'Japan''s best-known stock index of 225 large companies.'),
  ('microsoft', 'Microsoft', 'stock', 'Maker of Windows, Office and the Azure cloud; a major AI investor.'),
  ('amazon', 'Amazon', 'stock', 'Online retailer and owner of AWS, the largest cloud-computing business.'),
  ('alphabet', 'Alphabet', 'stock', 'Google''s parent company: search, YouTube, Android and Google Cloud.'),
  ('meta', 'Meta', 'stock', 'Owner of Facebook, Instagram and WhatsApp.'),
  ('amd', 'AMD', 'stock', 'Chipmaker competing with Intel in processors and with Nvidia in AI accelerators.'),
  ('tsmc', 'TSMC', 'stock', 'Taiwan''s contract chipmaker that manufactures chips for Apple, Nvidia and others.'),
  ('micron', 'Micron', 'stock', 'US maker of memory chips, which AI data centres need in large amounts.'),
  ('jpmorgan', 'JPMorgan Chase', 'stock', 'The largest US bank by assets.'),
  ('solana', 'Solana', 'crypto', 'A fast blockchain network; its coin is SOL.'),
  ('xrp', 'XRP', 'crypto', 'The coin linked to Ripple''s payments network.'),
  ('boj', 'Bank of Japan', 'central_bank', 'Japan''s central bank. It sets Japanese interest rates and can intervene in the yen.'),
  ('rba', 'Reserve Bank of Australia', 'central_bank', 'Australia''s central bank. It sets Australian interest rates.'),
  ('boc', 'Bank of Canada', 'central_bank', 'Canada''s central bank. It sets Canadian interest rates.'),
  ('snb', 'Swiss National Bank', 'central_bank', 'Switzerland''s central bank. It sets Swiss rates and manages the franc.')
on conflict (slug) do update set name = excluded.name, asset_type = excluded.asset_type, description_simple = excluded.description_simple;

insert into public.asset_aliases (asset_id, alias, is_case_sensitive)
select a.id, v.alias, v.cs from (values
  ('eur-usd', 'EUR/USD', false),
  ('eur-usd', 'EURUSD', false),
  ('eur-usd', 'euro-dollar', false),
  ('eur-usd', 'euro against the dollar', false),
  ('eur-usd', 'the euro', false),
  ('gbp-usd', 'GBP/USD', false),
  ('gbp-usd', 'GBPUSD', false),
  ('gbp-usd', 'sterling', false),
  ('gbp-usd', 'British pound', false),
  ('gbp-usd', 'the pound', false),
  ('usd-jpy', 'USD/JPY', false),
  ('usd-jpy', 'USDJPY', false),
  ('usd-jpy', 'Japanese yen', false),
  ('usd-jpy', 'the yen', false),
  ('usd-jpy', 'dollar-yen', false),
  ('gold', 'gold', false),
  ('gold', 'XAU', false),
  ('gold', 'XAU/USD', false),
  ('gold', 'bullion', false),
  ('gold', 'gold prices', false),
  ('silver', 'silver', false),
  ('silver', 'XAG', false),
  ('silver', 'XAG/USD', false),
  ('oil', 'crude oil', false),
  ('oil', 'oil prices', false),
  ('oil', 'crude', false),
  ('oil', 'Brent', true),
  ('oil', 'WTI', true),
  ('oil', 'OPEC', true),
  ('sp-500', 'S&P 500', false),
  ('sp-500', 'S&P500', false),
  ('sp-500', 'SPX', true),
  ('sp-500', 'Standard & Poor''s 500', false),
  ('nasdaq', 'Nasdaq', false),
  ('nasdaq', 'Nasdaq Composite', false),
  ('nasdaq', 'Nasdaq 100', false),
  ('nasdaq', 'NDX', true),
  ('nvidia', 'Nvidia', false),
  ('nvidia', 'NVDA', true),
  ('apple', 'Apple', true),
  ('apple', 'AAPL', true),
  ('apple', 'iPhone maker', false),
  ('tesla', 'Tesla', false),
  ('tesla', 'TSLA', true),
  ('bitcoin', 'Bitcoin', false),
  ('bitcoin', 'BTC', true),
  ('ethereum', 'Ethereum', false),
  ('ethereum', 'Ether', true),
  ('ethereum', 'ETH', true),
  ('fed', 'Federal Reserve', false),
  ('fed', 'the Fed', false),
  ('fed', 'Fed', true),
  ('fed', 'FOMC', true),
  ('fed', 'Powell', true),
  ('ecb', 'European Central Bank', false),
  ('ecb', 'ECB', true),
  ('ecb', 'Lagarde', true),
  ('boe', 'Bank of England', false),
  ('boe', 'BoE', true),
  ('boe', 'Andrew Bailey', false),
  ('aud-usd', 'AUD/USD', false),
  ('aud-usd', 'AUDUSD', false),
  ('aud-usd', 'Australian dollar', false),
  ('aud-usd', 'Aussie dollar', false),
  ('usd-cad', 'USD/CAD', false),
  ('usd-cad', 'USDCAD', false),
  ('usd-cad', 'Canadian dollar', false),
  ('usd-cad', 'loonie', false),
  ('usd-chf', 'USD/CHF', false),
  ('usd-chf', 'USDCHF', false),
  ('usd-chf', 'Swiss franc', false),
  ('dxy', 'US Dollar Index', false),
  ('dxy', 'U.S. Dollar Index', false),
  ('dxy', 'Dollar Index', false),
  ('dxy', 'DXY', true),
  ('dxy', 'greenback', false),
  ('natural-gas', 'natural gas', false),
  ('natural-gas', 'nat gas', false),
  ('natural-gas', 'Henry Hub', true),
  ('natural-gas', 'TTF', true),
  ('copper', 'copper', false),
  ('copper', 'HG=F', true),
  ('dow-jones', 'Dow Jones', false),
  ('dow-jones', 'the Dow', true),
  ('dow-jones', 'DJIA', true),
  ('dow-jones', 'Dow Jones Industrial Average', false),
  ('ftse-100', 'FTSE 100', false),
  ('ftse-100', 'FTSE', true),
  ('ftse-100', 'Footsie', false),
  ('dax', 'DAX', true),
  ('dax', 'DAX 40', true),
  ('nikkei-225', 'Nikkei 225', false),
  ('nikkei-225', 'Nikkei average', false),
  ('nikkei-225', 'Nikkei index', false),
  ('nikkei-225', 'the Nikkei', true),
  ('microsoft', 'Microsoft', false),
  ('microsoft', 'MSFT', true),
  ('amazon', 'Amazon', true),
  ('amazon', 'AMZN', true),
  ('amazon', 'Amazon Web Services', false),
  ('alphabet', 'Alphabet', true),
  ('alphabet', 'Google', true),
  ('alphabet', 'GOOGL', true),
  ('alphabet', 'GOOG', true),
  ('meta', 'Meta Platforms', false),
  ('meta', 'Meta', true),
  ('meta', 'META', true),
  ('amd', 'AMD', true),
  ('amd', 'Advanced Micro Devices', false),
  ('tsmc', 'TSMC', true),
  ('tsmc', 'Taiwan Semiconductor', false),
  ('micron', 'Micron', true),
  ('micron', 'Micron Technology', false),
  ('jpmorgan', 'JPMorgan Chase', false),
  ('jpmorgan', 'JPMorgan', false),
  ('jpmorgan', 'JPM', true),
  ('solana', 'Solana', false),
  ('solana', 'SOL', true),
  ('xrp', 'XRP', true),
  ('xrp', 'XRP/USD', false),
  ('boj', 'Bank of Japan', false),
  ('boj', 'BoJ', true),
  ('boj', 'BOJ', true),
  ('boj', 'Ueda', true),
  ('rba', 'Reserve Bank of Australia', false),
  ('rba', 'RBA', true),
  ('rba', 'Michele Bullock', false),
  ('boc', 'Bank of Canada', false),
  ('boc', 'Tiff Macklem', false),
  ('snb', 'Swiss National Bank', false),
  ('snb', 'SNB', true)
) as v(slug, alias, cs)
join public.assets a on a.slug = v.slug
on conflict (asset_id, alias) do update set is_case_sensitive = excluded.is_case_sensitive;

insert into public.sources (name, feed_url, site_domain, kind) values
  ('Federal Reserve', 'https://www.federalreserve.gov/feeds/press_all.xml', 'federalreserve.gov', 'central_bank'),
  ('European Central Bank', 'https://www.ecb.europa.eu/rss/press.html', 'ecb.europa.eu', 'central_bank'),
  ('Bank of England', 'https://www.bankofengland.co.uk/rss/news', 'bankofengland.co.uk', 'central_bank'),
  ('CNBC Finance', 'https://www.cnbc.com/id/10000664/device/rss/rss.html', 'cnbc.com', 'markets'),
  ('CNBC Economy', 'https://www.cnbc.com/id/20910258/device/rss/rss.html', 'cnbc.com', 'news'),
  ('MarketWatch Top Stories', 'https://feeds.content.dowjones.io/public/rss/mw_topstories', 'marketwatch.com', 'markets'),
  ('FXStreet', 'https://www.fxstreet.com/rss/news', 'fxstreet.com', 'markets'),
  ('CoinDesk', 'https://www.coindesk.com/arc/outboundfeeds/rss/', 'coindesk.com', 'markets'),
  ('OilPrice.com', 'https://oilprice.com/rss/main', 'oilprice.com', 'markets'),
  ('BBC Business', 'https://feeds.bbci.co.uk/news/business/rss.xml', 'bbc.co.uk', 'news'),
  ('Federal Reserve speeches', 'https://www.federalreserve.gov/feeds/speeches.xml', 'federalreserve.gov', 'central_bank'),
  ('Bank of Japan', 'https://www.boj.or.jp/en/rss/whatsnew.xml', 'boj.or.jp', 'central_bank'),
  ('Reserve Bank of Australia', 'https://www.rba.gov.au/rss/rss-cb-media-releases.xml', 'rba.gov.au', 'central_bank'),
  ('MarketWatch Bulletins', 'https://feeds.content.dowjones.io/public/rss/mw_bulletins', 'marketwatch.com', 'markets'),
  ('CNBC Technology', 'https://www.cnbc.com/id/19854910/device/rss/rss.html', 'cnbc.com', 'markets'),
  ('Yahoo Finance: big tech', 'https://feeds.finance.yahoo.com/rss/2.0/headline?s=NVDA,AAPL,TSLA,MSFT,AMZN,GOOGL,META&region=US&lang=en-US', 'finance.yahoo.com', 'markets'),
  ('Yahoo Finance: FX and commodities', 'https://feeds.finance.yahoo.com/rss/2.0/headline?s=EURUSD=X,GBPUSD=X,JPY=X,GC=F,CL=F,SI=F&region=US&lang=en-US', 'finance.yahoo.com', 'markets'),
  ('Investing.com News', 'https://www.investing.com/rss/news_25.rss', 'investing.com', 'markets'),
  ('Investing.com Forex', 'https://www.investing.com/rss/news_1.rss', 'investing.com', 'markets'),
  ('Investing.com Commodities', 'https://www.investing.com/rss/news_11.rss', 'investing.com', 'markets'),
  ('Seeking Alpha Market Currents', 'https://seekingalpha.com/market_currents.xml', 'seekingalpha.com', 'markets'),
  ('Cointelegraph', 'https://cointelegraph.com/rss', 'cointelegraph.com', 'markets'),
  ('Decrypt', 'https://decrypt.co/feed', 'decrypt.co', 'markets'),
  ('Guardian Economics', 'https://www.theguardian.com/business/economics/rss', 'theguardian.com', 'news')
on conflict (feed_url) do update set name = excluded.name, site_domain = excluded.site_domain, kind = excluded.kind;
