-- SignalDesk 003: seed the asset catalogue, aliases and verified sources.
-- GENERATED from src/config/assets-seed.ts and sources-seed.ts by `npm run seed -- --write-sql`. Do not edit by hand.

insert into public.assets (slug, name, asset_type, description_simple) values
  ('eur-usd', 'EUR/USD', 'currency_pair', 'How many US dollars one euro buys. Up means the euro is getting stronger against the dollar.'),
  ('gbp-usd', 'GBP/USD', 'currency_pair', 'How many US dollars one British pound buys. Up means sterling is getting stronger.'),
  ('usd-jpy', 'USD/JPY', 'currency_pair', 'How many Japanese yen one US dollar buys. Up means the dollar is stronger and the yen weaker.'),
  ('gold', 'Gold', 'commodity', 'The precious metal, often bought as a safe place for money when markets are nervous.'),
  ('silver', 'Silver', 'commodity', 'A precious metal also used heavily in industry, such as solar panels and electronics.'),
  ('oil', 'Crude oil', 'commodity', 'The price of crude oil (Brent and WTI benchmarks), driven by supply, demand and OPEC decisions.'),
  ('sp-500', 'S&P 500', 'index', 'An index of 500 large US companies, the most watched measure of the US stock market.'),
  ('nasdaq', 'Nasdaq', 'index', 'A US stock index dominated by technology companies.'),
  ('nvidia', 'NVIDIA', 'stock', 'Chipmaker whose graphics processors power much of today''s AI.'),
  ('apple', 'Apple', 'stock', 'Maker of the iPhone, Mac and related services; one of the world''s largest companies.'),
  ('tesla', 'Tesla', 'stock', 'Electric-car and battery company.'),
  ('bitcoin', 'Bitcoin', 'crypto', 'The largest cryptocurrency by market value.'),
  ('ethereum', 'Ethereum', 'crypto', 'The second-largest cryptocurrency network; its coin is called ether.'),
  ('fed', 'Federal Reserve', 'central_bank', 'The US central bank. It sets US interest rates to keep prices stable and jobs strong.'),
  ('ecb', 'European Central Bank', 'central_bank', 'The central bank for the euro area. It sets interest rates for the countries using the euro.'),
  ('boe', 'Bank of England', 'central_bank', 'The UK central bank. It sets UK interest rates.')
on conflict (slug) do update set name = excluded.name, asset_type = excluded.asset_type, description_simple = excluded.description_simple;

insert into public.asset_aliases (asset_id, alias, is_case_sensitive)
select a.id, v.alias, v.cs from (values
  ('eur-usd', 'EUR/USD', false),
  ('eur-usd', 'EURUSD', false),
  ('eur-usd', 'euro-dollar', false),
  ('eur-usd', 'euro against the dollar', false),
  ('eur-usd', 'the euro', false),
  ('gbp-usd', 'GBP/USD', false),
  ('gbp-usd', 'GBPUSD', false),
  ('gbp-usd', 'sterling', false),
  ('gbp-usd', 'British pound', false),
  ('gbp-usd', 'the pound', false),
  ('usd-jpy', 'USD/JPY', false),
  ('usd-jpy', 'USDJPY', false),
  ('usd-jpy', 'Japanese yen', false),
  ('usd-jpy', 'the yen', false),
  ('usd-jpy', 'dollar-yen', false),
  ('gold', 'gold', false),
  ('gold', 'XAU', false),
  ('gold', 'XAU/USD', false),
  ('gold', 'bullion', false),
  ('gold', 'gold prices', false),
  ('silver', 'silver', false),
  ('silver', 'XAG', false),
  ('silver', 'XAG/USD', false),
  ('oil', 'crude oil', false),
  ('oil', 'oil prices', false),
  ('oil', 'crude', false),
  ('oil', 'Brent', true),
  ('oil', 'WTI', true),
  ('oil', 'OPEC', true),
  ('sp-500', 'S&P 500', false),
  ('sp-500', 'S&P500', false),
  ('sp-500', 'SPX', true),
  ('sp-500', 'Standard & Poor''s 500', false),
  ('nasdaq', 'Nasdaq', false),
  ('nasdaq', 'Nasdaq Composite', false),
  ('nasdaq', 'Nasdaq 100', false),
  ('nasdaq', 'NDX', true),
  ('nvidia', 'Nvidia', false),
  ('nvidia', 'NVDA', true),
  ('apple', 'Apple', true),
  ('apple', 'AAPL', true),
  ('apple', 'iPhone maker', false),
  ('tesla', 'Tesla', false),
  ('tesla', 'TSLA', true),
  ('bitcoin', 'Bitcoin', false),
  ('bitcoin', 'BTC', true),
  ('ethereum', 'Ethereum', false),
  ('ethereum', 'Ether', true),
  ('ethereum', 'ETH', true),
  ('fed', 'Federal Reserve', false),
  ('fed', 'the Fed', false),
  ('fed', 'Fed', true),
  ('fed', 'FOMC', true),
  ('fed', 'Powell', true),
  ('ecb', 'European Central Bank', false),
  ('ecb', 'ECB', true),
  ('ecb', 'Lagarde', true),
  ('boe', 'Bank of England', false),
  ('boe', 'BoE', true),
  ('boe', 'Andrew Bailey', false)
) as v(slug, alias, cs)
join public.assets a on a.slug = v.slug
on conflict (asset_id, alias) do update set is_case_sensitive = excluded.is_case_sensitive;

insert into public.sources (name, feed_url, site_domain, kind) values
  ('Federal Reserve', 'https://www.federalreserve.gov/feeds/press_all.xml', 'federalreserve.gov', 'central_bank'),
  ('European Central Bank', 'https://www.ecb.europa.eu/rss/press.html', 'ecb.europa.eu', 'central_bank'),
  ('Bank of England', 'https://www.bankofengland.co.uk/rss/news', 'bankofengland.co.uk', 'central_bank'),
  ('CNBC Finance', 'https://www.cnbc.com/id/10000664/device/rss/rss.html', 'cnbc.com', 'markets'),
  ('CNBC Economy', 'https://www.cnbc.com/id/20910258/device/rss/rss.html', 'cnbc.com', 'news'),
  ('MarketWatch Top Stories', 'https://feeds.content.dowjones.io/public/rss/mw_topstories', 'marketwatch.com', 'markets'),
  ('FXStreet', 'https://www.fxstreet.com/rss/news', 'fxstreet.com', 'markets'),
  ('CoinDesk', 'https://www.coindesk.com/arc/outboundfeeds/rss/', 'coindesk.com', 'markets'),
  ('OilPrice.com', 'https://oilprice.com/rss/main', 'oilprice.com', 'markets'),
  ('BBC Business', 'https://feeds.bbci.co.uk/news/business/rss.xml', 'bbc.co.uk', 'news')
on conflict (feed_url) do update set name = excluded.name, site_domain = excluded.site_domain, kind = excluded.kind;
